apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-cost-optimizer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-cost-optimizer
  template:
    metadata:
      labels:
        app: cloud-cost-optimizer
    spec:
      containers:
      - name: optimizer
        image: siddhantsaxena45/cloud-cost-optimizer:latest
        ports:
        - containerPort: 3000
